#!/usr/bin/env ruby

# borrowed from http://glxn.net/2014/01/05/git-commit-message-hook-for-jira-issue-tags/
message_file = ARGV[0]
message = File.read(message_file)

$regex = /^(?!#)(.*?)([A-Z0-9]+-\d+)/

if !$regex.match(message)
  head = File.read("./.git/HEAD")
  branch = $regex.match(head)
  tag_exists = $regex.match(message)
  if (branch && branch.length == 3 && !tag_exists)
    File.open(message_file, "w") {|f| f.write(branch[2] + ": " + message) }
    exit 0
  end

  puts "[ERROR] Your message is missing JIRA issue tag"
  exit 1
end
